### ISSUE TITLE
Sparsifying the small matrix

### ISSUE THREAD

**Issue by Xiaohui9607** [chongminggao/KuaiRec#1]
Hi, I read the paper and it says the small matrix is collected in 2 stage -- first the usual recommendation rule (stage 1), then for the pairs with missing values, the system is modified to make the missing items exposed to the users (stage 2).

Are there any records we can get to see which pairs are collected in stage 1 and which are collected in stage 2?

Thanks!

**Comment by chongminggao** [comment]
Hi @Xiaohui9607, as you can see that the small matrix has the fields "time", "date", and "timestamp". The three fields are "None" for certain interactions. You can use this as an indicator showing whether the data are recorded in stage 1 (i.e., having values for the time field) or collected in stage 2 (i.e., which is "None" for the time field).

The date distribution of the small matrix is drawn as follows:
![date distribution of small matrix](https://user-images.githubusercontent.com/11169881/184106338-489676b4-21d1-435b-83b9-855fb278a68a.png)
